# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d036798b69520f16bbda588e74c6f4fb1128d62fc4113cb51093e4ddec4d9f0de1c546902b3d72e50a9101ac8f00387eaf41a276ce3de8ec872886c1536899c

test:
  secret_key_base: a9f8dbaa639da2b9bd3bf6b2e65640e84f5b546f90d8f8490f0e72bfab1e5a32441a7fd3cbb3f07d527f02f7476383bff0557f9014010a5cb0a90725089f4314

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
